name: Generate Space Shooter GIF

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at 00:00 UTC
  workflow_dispatch:       # Allows manual run from Actions tab

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Space Shooter
        uses: czl9707/gh-space-shooter@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_name: dist/github-snake.gif

      - name: Push to repository
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
